import type {
  MessageContent,
  NormalizedMessage,
  ReplyContext,
} from '../transcript/types';
import {
  EMBEDDED_CONTENT_SELECTOR,
  MEDIA_SELECTOR,
  MESSAGE_ACTIONS_SELECTOR,
  OUTGOING_MESSAGE_SELECTOR,
  PROFILE_LINK_SELECTOR,
  REPLY_SELECTOR,
  REPLY_SENDER_SELECTOR,
  SENDER_SELECTOR,
  SHARED_POST_PERMALINK_SELECTOR,
  TEXT_CONTENT_SELECTOR,
  TIME_SELECTOR,
} from './selectors';

export interface ParseMessageContext {
  date?: string;
  scroller?: HTMLElement;
}

const AI_PRESENTATION_LABELS = new Set(['Generated by AI']);

export function parseMessage(
  root: HTMLElement,
  context: ParseMessageContext = {},
): NormalizedMessage | null {
  const initialSender = parseSender(root, context, false);
  const content = parseContent(root, initialSender);
  if (!content) return null;

  const allowLayoutInference =
    content.type === 'text' || content.type === 'shared-post';
  const sender =
    initialSender === 'Unknown' && allowLayoutInference
      ? parseSender(root, context, true)
      : initialSender;
  const time = normalizeInline(
    root.querySelector<HTMLElement>(TIME_SELECTOR)?.textContent ?? '',
  );
  const date = normalizeInline(context.date ?? '');
  const timestamp = time
    ? { time, ...(date ? { date } : {}) }
    : undefined;
  const reply = parseReply(root);
  const signature = JSON.stringify({
    content,
    ...(reply ? { replyPreview: reply.preview } : {}),
  });

  return {
    signature,
    sender,
    ...(timestamp ? { timestamp } : {}),
    content,
    ...(reply ? { reply } : {}),
  };
}

function parseSender(
  root: HTMLElement,
  context: ParseMessageContext,
  allowLayoutInference: boolean,
): string {
  if (root.matches(OUTGOING_MESSAGE_SELECTOR)) return 'You';

  const visibleSender = Array.from(
    root.querySelectorAll<HTMLElement>(SENDER_SELECTOR),
  )
    .filter((candidate) => !isInsideEmbeddedContent(candidate, root))
    .map((candidate) => normalizeInline(candidate.textContent ?? ''))
    .find(Boolean);
  if (visibleSender) return visibleSender;

  const profileSender = parseProfileSender(findMessageLevelProfileLink(root));
  if (profileSender) return profileSender;

  return inferSenderFromGeometry(root, context, allowLayoutInference);
}

function inferSenderFromGeometry(
  root: HTMLElement,
  context: ParseMessageContext,
  allowLayoutInference: boolean,
): string {
  const { scroller } = context;
  if (!scroller) return 'Unknown';

  const contentRoot = findMessageLevelContentRoot(root);
  if (allowLayoutInference && hasOutgoingLayout(contentRoot, root)) return 'You';

  const rootRect = contentRoot.getBoundingClientRect();
  const scrollerRect = scroller.getBoundingClientRect();
  if (rootRect.width <= 0 || scrollerRect.width <= 0) return 'Unknown';

  const rootCenter = rootRect.left + rootRect.width / 2;
  const scrollerCenter = scrollerRect.left + scrollerRect.width / 2;
  if (rootCenter > scrollerCenter) return 'You';
  return 'Unknown';
}

function findMessageLevelProfileLink(
  root: HTMLElement,
): HTMLAnchorElement | null {
  return (
    Array.from(
      root.querySelectorAll<HTMLAnchorElement>(PROFILE_LINK_SELECTOR),
    ).find((candidate) => !isInsideEmbeddedContent(candidate, root)) ?? null
  );
}

function isInsideEmbeddedContent(
  candidate: Element,
  root: HTMLElement,
): boolean {
  const sharedPermalink = candidate
    .closest<HTMLElement>('[role="button"]')
    ?.querySelector(SHARED_POST_PERMALINK_SELECTOR);
  if (sharedPermalink) return true;

  const embedded = candidate.closest(EMBEDDED_CONTENT_SELECTOR);
  return embedded !== null && embedded !== root;
}

function findMessageLevelContentRoot(root: HTMLElement): HTMLElement {
  const specializedCard = root
    .querySelector(SHARED_POST_PERMALINK_SELECTOR)
    ?.closest<HTMLElement>('[role="button"]');
  const candidate =
    specializedCard?.parentElement ??
    findLeafTextNodes(root)
      .filter((element) => !isInsideEmbeddedContent(element, root))
      .at(-1) ??
    findMedia(root) ??
    root;

  return candidate;
}

function hasOutgoingLayout(
  contentRoot: HTMLElement,
  messageRoot: HTMLElement,
): boolean {
  let candidate: HTMLElement | null = contentRoot;

  while (candidate && messageRoot.contains(candidate)) {
    const style = getComputedStyle(candidate);
    const parent = candidate.parentElement;
    const parentStyle = parent ? getComputedStyle(parent) : undefined;
    if (
      style.display === 'flex' &&
      style.alignItems === 'center' &&
      style.flexDirection === 'row-reverse' &&
      parentStyle?.display === 'flex' &&
      parentStyle.alignItems === 'flex-end' &&
      parentStyle.justifyContent === 'flex-end'
    ) {
      return true;
    }
    if (candidate === messageRoot) break;
    candidate = candidate.parentElement;
  }

  return false;
}

function parseContent(
  root: HTMLElement,
  sender: string,
): MessageContent | null {
  const sharedPost = parseSharedPost(root);
  if (sharedPost) return sharedPost;

  if (sender.toLocaleLowerCase() === 'meta ai') {
    const answer = parseMetaAiAnswer(root);
    return answer ? { type: 'text', text: answer } : null;
  }

  const textRoot =
    root.querySelector<HTMLElement>(TEXT_CONTENT_SELECTOR) ??
    findLeafTextNodes(root).at(-1);
  const text = normalizeMultiline(textRoot?.textContent ?? '');
  const media = findMedia(root);
  const label = media ? parseMediaLabel(media) : '';

  if (text && label) return { type: 'mixed', text, label };
  if (text) return { type: 'text', text };
  if (label) return { type: 'media', label };
  return null;
}

function parseSharedPost(root: HTMLElement): MessageContent | null {
  const permalink = root.querySelector<HTMLAnchorElement>(
    SHARED_POST_PERMALINK_SELECTOR,
  );
  const card = permalink?.closest<HTMLElement>('[role="button"]');
  if (!card) return null;

  const source = parseProfileSender(
    card.querySelector<HTMLAnchorElement>(PROFILE_LINK_SELECTOR),
  );
  const caption = findLeafTextNodes(card)
    .filter((candidate) => !candidate.closest(PROFILE_LINK_SELECTOR))
    .map((candidate) => normalizeMultiline(candidate.textContent ?? ''))
    .filter(Boolean)
    .join('\n');

  if (!source && !caption) return null;
  return {
    type: 'shared-post',
    ...(source ? { source } : {}),
    ...(caption ? { caption } : {}),
  };
}

function parseMetaAiAnswer(root: HTMLElement): string {
  return findLeafTextNodes(root)
    .filter((candidate) => !candidate.closest(REPLY_SELECTOR))
    .filter((candidate) => !candidate.closest(PROFILE_LINK_SELECTOR))
    .filter((candidate) => !candidate.closest(MESSAGE_ACTIONS_SELECTOR))
    .map((candidate) => normalizeMultiline(candidate.textContent ?? ''))
    .filter((text) => text && !AI_PRESENTATION_LABELS.has(text))
    .join('\n');
}

function parseMediaLabel(media: HTMLElement): string {
  const explicitKind = normalizeInline(media.dataset.mediaKind ?? '');
  if (explicitKind) return explicitKind.toLowerCase();

  if (media instanceof HTMLImageElement) {
    return normalizeInline(media.alt).toLowerCase() || 'image';
  }
  if (media instanceof HTMLVideoElement) return 'video';
  if (media instanceof HTMLAudioElement) return 'audio';

  return normalizeInline(media.getAttribute('aria-label') ?? '').toLowerCase();
}

function parseReply(root: HTMLElement): ReplyContext | undefined {
  const replyRoot =
    root.querySelector<HTMLElement>(REPLY_SELECTOR) ??
    findStructuralReply(root);
  if (!replyRoot) return undefined;

  const preview = normalizeMultiline(
    replyRoot.querySelector<HTMLElement>('[dir="auto"]')?.textContent ??
      replyRoot.textContent ??
      '',
  );
  if (!preview) return undefined;

  const sender = normalizeInline(
    replyRoot.querySelector<HTMLElement>(REPLY_SENDER_SELECTOR)?.textContent ?? '',
  );

  return {
    ...(sender ? { sender } : {}),
    preview,
  };
}

function parseProfileSender(link: HTMLAnchorElement | null): string {
  if (!link) return '';

  const imageAlt = normalizeInline(
    link.querySelector<HTMLImageElement>('img[alt]')?.alt ?? '',
  );
  if (imageAlt && imageAlt !== 'user-profile-picture') return imageAlt;

  const label = normalizeInline(link.getAttribute('aria-label') ?? '');
  const labelledSender = label.match(
    /^(?:Profile of |Open the profile page of )(.+)$/u,
  )?.[1];
  if (labelledSender) return labelledSender;

  return normalizeInline(link.getAttribute('href') ?? '')
    .replace(/^\//u, '')
    .replace(/\/$/u, '');
}

function findLeafTextNodes(root: HTMLElement): HTMLElement[] {
  return Array.from(root.querySelectorAll<HTMLElement>('[dir="auto"]')).filter(
    (candidate) => candidate.querySelector('[dir="auto"]') === null,
  );
}

function findMedia(root: HTMLElement): HTMLElement | null {
  const explicitMedia = root.querySelector<HTMLElement>(MEDIA_SELECTOR);
  if (explicitMedia) return explicitMedia;

  return (
    Array.from(
      root.querySelectorAll<HTMLElement>('img[alt], video, audio'),
    ).find((candidate) => {
      if (candidate.closest(PROFILE_LINK_SELECTOR)) return false;
      if (candidate.closest('[aria-label="Message actions"]')) return false;
      return candidate.getAttribute('alt') !== 'user-profile-picture';
    }) ?? null
  );
}

function findStructuralReply(root: HTMLElement): HTMLElement | null {
  const contentRoot = findLeafTextNodes(root).at(-1);
  if (!contentRoot) return null;

  return (
    Array.from(root.querySelectorAll<HTMLElement>('[role="button"]')).find(
      (candidate) => {
        if (!normalizeMultiline(candidate.textContent ?? '')) return false;
        if (candidate.querySelector('img, video, audio')) return false;
        if (candidate.contains(contentRoot)) return false;
        return Boolean(
          candidate.compareDocumentPosition(contentRoot) &
            Node.DOCUMENT_POSITION_FOLLOWING,
        );
      },
    ) ?? null
  );
}

function normalizeInline(value: string): string {
  return value.trim().replace(/\s+/gu, ' ');
}

function normalizeMultiline(value: string): string {
  return value
    .replace(/\r\n?/gu, '\n')
    .split('\n')
    .map(normalizeInline)
    .filter(Boolean)
    .join('\n');
}
